version: '3.8'
services:
  express-server:
    build: ./express-server
    ports:
      - "5000:5000"
    env_file:
      - ./express-server/.env
    environment:
      NODE_ENV: development

  react-app:
    build: ./react-app
    ports:
      - "3000:3000"
    environment: 
      API: 'http://3.208.28.247:5000'
      GOOGLE_API_KEY: 'AIzaSyCePkfLfau3i98g4UC4AnOvt5Qnc-5DCHI'
