version: '3.8'
services:
  
  express-server:
    build: ./express-server
    ports:
      - "5000:5000"
    volumes:
      - ./express-server:/usr/src/app
    environment:
      NODE_ENV: development
      DATABASE_URL : 'postgresql://shunodb:CSE+JnU-2024@shunodb.ccsmmzgh5uxt.us-east-1.rds.amazonaws.com:5432/shunodb'
      GOOGLE_API_KEY : 'AIzaSyBDnCKjtcNXHUsKl4yGKY9JN9lQvpTwxpg'
      PORT : 5000
      AWS_ACCESS_KEY_ID : "AKIATUHQJFZDBMUPHTFW"
      AWS_SECRET_ACCESS_KEY : "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"
      AWS_REGION : "us-east-1"

  react-app:
    build: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      API :  http://localhost:5000/api
